### PR TITLE
Remove external.xx.fbcdn.net

### PR DESCRIPTION
**Pull request by p1r473**
This is a Facebook Content Delivery Network (CDN) and delivers static images and resources
This breaks images/thumbnails in FB Messenger

Also please open up Github Issues so I can create issues as opposed to only pull requests
Thanks!

@34730

### CODE REVIEW

**Comment by p1r473** [comment]
Bump @34730

**Comment by 34730** [comment]
@p1r473 I didn't see this then. I'm a little surprised there's a pull request.

**Comment by p1r473** [comment]
Bump @34730

**Comment by 34730** [comment]
https://github.com/34730/Adaway/commit/c60e17558d405ad2fe8b9f428b71cdca90a3b4c5

**Pull request closed without merging**
